"""Routes still awaiting a response model. SHRINKS ONLY."""

ALLOWLIST = {
    "DELETE /api/v2/simulation/scenarios/{scenario_id}",
    "GET /api/attendance/kpi/bradford-factor/{employee_id}",
    "GET /api/attendance/statistics/summary",
    "GET /api/capacity/kpi/variance",
    "GET /api/jobs/{job_id}/dpmo",
    "GET /api/jobs/{job_id}/efficiency",
    "GET /api/jobs/{job_id}/kpi-summary",
    "GET /api/jobs/{job_id}/performance",
    "GET /api/jobs/{job_id}/ppm",
    "GET /api/jobs/{job_id}/yield",
    "GET /api/onboarding/status",
    "GET /api/pivot/{dataset}",
    "GET /api/pivot/{dataset}/csv",
    "GET /api/quality/kpi/quality-score",
    "GET /api/quality/statistics/summary",
    "GET /api/work-orders/{work_order_id}/rty",
    "POST /api/attendance/bulk",
    "POST /api/attendance/mark-all-present",
    "POST /api/auth/change-password",
    "POST /api/auth/forgot-password",
    "POST /api/auth/logout",
    "POST /api/auth/reset-password",
    "POST /api/capacity/scenarios/compare",
    "POST /api/defect-types/upload/{client_id}",
    "POST /api/floating-pool/simulation/optimize-allocation",
    "POST /api/floating-pool/simulation/shift-coverage",
    "POST /api/hold-catalogs/seed-defaults",
    "POST /api/reports/email-config/test",
    "POST /api/reports/send-manual",
    "POST /api/workflow/bulk-transition",
    "POST /api/workflow/config/{client_id}/apply-template",
    "POST /api/workflow/work-orders/{work_order_id}/transition",
    "POST /api/workflow/work-orders/{work_order_id}/validate",
    "PUT /api/kpi-thresholds",
    "PUT /api/workflow/config/{client_id}",
}
